config/routes.rb
Rails.application.routes.draw do
  root 'hotels#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :hotels do
    resources :reviews
  end

  resources :users

  get 'restaurants' => 'restaurants#index'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base

	has_many :reviews, dependent: :destroy

	validates :title, presence: true
	validates :body, length: {minimum: 10}
	validates :price, numericality: {greater_than_or_equal_to: 0}
	validates :image, allow_blank: true, format: {
		with: /\w+\.(gif|jpg|png)\z/i,
		message: "must be a valid image (GIF, JPG or PNG)"
	}

	def self.without_reviews
		includes(:reviews).where(:reviews => {:id => nil})
	end

	def self.with_reviews
		includes(:reviews).where.not(:reviews => {:id => nil})
	end

	def self.luxury_hotels
		where("price > 100")
	end

	def self.bargain_hotels
		where("price <= 100")
	end

	def self.luxury_price_range_min
		where("price > 100").minimum("price")
	end

	def self.luxury_price_range_max
		where("price > 100").maximum("price")
	end

	def self.bargain_price_range_min
		where("price <= 100").minimum("price")
	end

	def self.bargain_price_range_max
		where("price <= 100").maximum("price")
	end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :hotel
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator

	def validate_each(record, attribute, value)
		unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			record.errors[attribute] << (options[:message] || "is not an email")
		end
	end
end

class User < ActiveRecord::Base

	before_save :downcase_email

	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 200}
	validates :email, email: true
	validates :email, uniqueness: {case_sensitive: false}
	validates :password, length: {minimum: 5}

	has_secure_password

	private

	def downcase_email

		self.email = email.downcase

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

	before_action :require_login, only: [:show, :edit, :update, :new, :create, :destroy]

	def index
		@hotels = Hotel.all
		@hotels = Hotel.order(title: :asc)
		@luxury_hotels = Hotel.luxury_hotels
		@bargain_hotels = Hotel.bargain_hotels
		@luxury_price_range_min = Hotel.luxury_price_range_min
		@luxury_price_range_max = Hotel.luxury_price_range_max
		@bargain_price_range_min = Hotel.bargain_price_range_min
		@bargain_price_range_max = Hotel.bargain_price_range_max
		@all_hotels = Hotel.all
		@reviewed_hotels = Hotel.with_reviews
		@unreviewed_hotels = Hotel.without_reviews
	end

	def show
		@hotel = Hotel.find(params[:id])
	end

	def edit
		@hotel = Hotel.find(params[:id])
	end

	def update
		@hotel = Hotel.find(params[:id])
		if @hotel.update(hotel_params)
			flash[:notice] = "Congrats! You successfully updated this Hotel"
			redirect_to hotel_path(@hotel)
		else
			render :edit
		end
	end

	def new
		@hotel = Hotel.new
	end

	def create
		@hotel = Hotel.new(hotel_params)

		if(@hotel.save)
			redirect_to hotel_path(@hotel)
		else
			render :new
		end
	end

	def destroy
		Hotel.find(params[:id]).destroy
		redirect_to hotels_path
	end

	private

	def hotel_params
		params.require(:hotel).permit(:title, :body, :price)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index

		@restaurants = Restaurant.all

	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :require_login, only: [:new, :create]

	def index

		@reviews = find_hotel.reviews

	end

	def new

		@review = find_hotel.reviews.new

	end

	def create

		@hotel = find_hotel
		@review = @hotel.reviews.new(review_params)
		@hotel.save
		redirect_to hotel_path(@hotel)

	end

	private

	def find_hotel

		@hotel = Hotel.find(params[:hotel_id])

	end

	def review_params

		params.require(:review).permit(:body)

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

  	user = User.find_by(email: params[:email].downcase)
  	if user && user.authenticate(params[:password])
  		log_in(user)
  		redirect_to user_path(user)
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: [:show]

  def new

  	@user = User.new

  end

  def create

  	@user = User.new(user_params)

  	if(@user.save)
  		log_in(@user)
  		flash[:success] = "Welcome to this funky page which has some hotels on it!"
  		redirect_to user_path(@user)
  	else
  		render :new
  	end
  end

  def show

  	@user = User.find(params[:id])

  end

  private

  def user_params

  	params.require(:user).permit(:name, :email, :password, :password_confirmation)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
	 def format_body(hotel)
        if hotel.body.present?
            # note you can call a helper from a helper
            hotel.body
        else
            content_tag(:i, 'n/a')
        end
    end

    def format_price(hotel)
    	if hotel.body.present?
    		hotel.price
    	else
    		content_tag(:i, 'On Request')
    	end
    end

    def format_image(hotel)
        if hotel.body.present?
            hotel.image
        else
            content_tag(:i, 'Not Available')
        end
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
	<p>This form contains <%= pluralize(@hotel.errors.count, "error") %></p>
	<ul>
	<% @hotel.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title, autofocus: true %>
	</p>
	<p>
		<%= f.label :body %>
	</p>
	<p>
		<%= f.text_area :body, cols: 30, rows: 10 %>
	</p>
	<p>
		<%= f.label :price %>
		<%= f.number_field :price %>
	</p>
	<p>
		<%= f.submit 'Submit', class: 'btn btn-info' %>
    </p>
<% end %>

app/views/hotels/_hotel.html.erb
<div>
	<h4><%= hotel.title %></h4>
	<p><%= format_body(hotel) %></p>
    <p><%= link_to(pluralize(hotel.reviews.count, "review"), hotel_reviews_path(hotel))  %></p>
    <p><%= link_to "Show", hotel_path(hotel) %> | <%= link_to "Edit", edit_hotel_path(hotel) %> |  <%= link_to "Delete", hotel_path(hotel), method: :delete, data: {confirm: "Would you like to delete this?"} %></p>
</div>

app/views/hotels/_hotels.html.erb
<!-- <table class="table table-hover table-bordered table-striped">
  <caption><%= caption %></caption>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Reviews</th>
    <th></th>    
  </tr>
  <% hotels.each do | hotel | %>  
  <tr>
    <td><%= link_to(hotel.title,  hotel_path(hotel)) %></td>
    <td><%= format_body(hotel) %></td>
    <td><%= link_to(hotel.reviews.count, hotel_reviews_path(hotel)) %></td>
    <td>
      <%= link_to "Show", hotel_path(hotel) %> | 
      <%= link_to "Edit", edit_hotel_path(hotel) %> | 
      <%= link_to "Delete", hotel_path(hotel), method: :delete, data: {confirm: "Would you like to delete this?"} %>

    </td>
  </tr>
  <% end %>
</table> -->

<div>
  <h3><%= caption %></h3>
    <%= render partial: hotels, spacer_template: "shared/break" %>
</div>

app/views/hotels/edit.html.erb
<h3><%= @hotel.title %></h3>

<%= render('form') %>

app/views/hotels/index.html.erb
<div class="jumbotron">
  <h1>Hello, Hotel Goers!</h1>
</div>
<div class="page-header">
  <h1>Hotels <small>Good Hotels</small></h1>
</div>

<h3><%= pluralize(@hotels.count, 'Hotels') %></h3>

<p>These are <%= @hotels.count %> lovely-jubbly hotels:</p>

<%= render partial: "hotels", object: @all_hotels, locals: {caption: "All Hotels"} %>
<%= render partial: "hotels", object: @unreviewed_hotels, locals: {caption: "Unreviewed Hotels"} %>
<%= render partial: "hotels", object: @reviewed_hotels, locals: {caption: "Reviewed Hotels"} %>

<div class="row">
	<div class="col-xs-3 col-xs-offset-3">
		<p><a class="btn btn-info" href="/restaurants" role="button">See some Restaurants</a></p>
	</div>
	<div class="col-xs-3">
		<p><a class="btn btn-primary" href="<%= new_hotel_path(@hotel) %>" role="button">Add a New Hotel</a></p>
	</div>
</div>

app/views/hotels/new.html.erb
<h3>New Hotel</h3>

<%= render('form') %>

app/views/hotels/show.html.erb
<h3><%= @hotel.title %></h3>

<p><%= @hotel.body %></p>

<%= image_tag("Default Hotel.jpg", size: "300", alt: "This a a picture of the Hotel") %>

<%= link_to "Add a Review", new_hotel_review_path(@hotel) %> | 
<%= link_to "Back to Hotels", hotels_path %> | 
<%= link_to "Edit", edit_hotel_path(@hotel) %> | 
<%= link_to "Delete", hotel_path(@hotel), mehtod: :delete, data: {confirm: "Would you like to delete this?"} %>

<p>Reviews</p>

<%= render partial: "reviews/review", collection: @hotel.reviews %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Explore</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user) %> |
    <%= link_to "Log Out", logout_path, method: "delete" %>

  <% else %>
    <%= link_to "Log In", login_path %> | 
    <%= link_to "Sign Up", new_user_path %>
  <% end %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/restaurants/index.html.erb
<h3><%= pluralize(@restaurants.count, 'Restaurants') %></h3>

<p>These are <%= @restaurants.count %> lovely-jubbly restaurants:</p>

<table border="2px solid black">
	<thead>
		<tr>
			<th>Title</th>
			<th>Posted On</th>
		</tr>
	</thead>
	<tbody>
		<% @restaurants.each do |restaurant| %>
		<tr>
			<td><%= restaurant.title %></td>
			<td><%= restaurant.created_at.to_s(:short) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<p><a href="/hotels">Back to the Hotels</a></p>

app/views/reviews/_review.html.erb
<div>
	<p>
		<%= review.body %>
		<br/>
		Reviewed <%= time_ago_in_words(review.created_at) %> ago
	</p>
</div>

app/views/reviews/index.html.erb
<h3>Reviews</h3>

<p><%= @hotel.title %></p>

<p>Reviews</p>

<%= render partial: @reviews, spacer_template: "shared/break" %>

<div class="row">
	<div class="col-xs-3 col-xs-offset-5">
		<p><a class="btn btn-primary" href="<%= hotels_path %>" role="button">Back to Hotels</a></p>
	</div>
</div>

app/views/reviews/new.html.erb
<h3>New review for: <%= @hotel.title %></h3>

<%= form_for([@hotel, @review]) do | f | %>
    <p>
        <%= f.label :body, "Please enter your review" %>
    </p>
    <p> 
        <%= f.text_area :body, cols: 30, rows: 10 %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/shared/_break.html.erb
<hr>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<p>The form contains <%= pluralize(@user.errors.count, "error") %></p>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :name %>
	</p>
	<p>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %>
	</p>
	<p>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %>
	</p>
	<p>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation, "Confirmation" %>
	</p>
	<p>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.submit "Sign Up", class: "btn btn-primary" %>
	</p>
<% end %>

app/views/users/show.html.erb
<h3>Profile</h3>

<table>
	<tr><td>Name:</td><td><%= @user.name %></td></tr>
	<tr><td>Email:</td><td><%= @user.email %></td></tr>
</table>